### PR TITLE
Added gateoverflow answer keys link and note.

### PR DESCRIPTION
**Pull request by chavanshashank**
Added gateoverflow answer keys link and note on front page of marks calc.

### CODE REVIEW

**Comment by viv696** [comment]
the  code only stores marks and id.the problem with this model is IISC will relase the official keys and there will be some answers which  differ from gateoverflow keys.so instead you should have stored the responses/response link as well so in case of new keys old responses can be used to reevaluate marks.
i am talking about this.
    $strings = array('id' => $id, 'marks' => $marks);
should change to 
        $strings = array('id' => $id, 'marks' => $marks,'response_link'=>response_url);

**Comment by AgarwalPragy** [comment]
@viv696: No, that would be a massive privacy concern. We are currently logging data anonymously, and logging URLs would enable anyone to see the user's name.

**Comment by AgarwalPragy** [comment]
@chavanshashank : Hey thanks! Sorry about the delay, I'm new to github :P

**Comment by chavanshashank** [comment]
No problem. Keep it up :+1:  :smile:

**Pull request merged**
